services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - zenclik-net

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./docker/.env.server
    depends_on:
      - mongodb
    networks:
      - zenclik-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3001:80"
    depends_on:
      - mongodb
    networks:
      - zenclik-net

volumes:
  mongo-data:

networks:
  zenclik-net:
    driver: bridge
